when:
  - event: [push, manual]

clone:
  git:
    image: ${DOCKER_PREFIX}/network-utils
    pull: true
    commands:
      - git clone ${CI_REPO_CLONE_URL} project
      - cd project
      - git checkout ${CI_COMMIT_SHA}
      - git submodule update --init --recursive
      - export REPO_REVISION=`git rev-list HEAD --count`
      - echo "ARTIFACT_PREFIX=${CI_REPO_NAME}_r$${REPO_REVISION}-${CI_COMMIT_SHA:0:8}_b${CI_PIPELINE_NUMBER}" >> envvars

steps:
  build_deb:
    image: ${DOCKER_PREFIX}/gcc-arm-embedded
    pull: true
    commands:
      - cd project
      - cmake . -B build-deb -DCMAKE_BUILD_TYPE=Debug
      - make -C build-deb -j `nproc`
      - cmake . -B build-deb_nor -DTARGET_NOR=ON -DUSE_DFU=ON -DCMAKE_BUILD_TYPE=Debug
      - make -C build-deb_nor -j `nproc`
      - cmake . -B build-deb_sram -DTARGET_SRAM=ON -DCMAKE_BUILD_TYPE=Debug
      - make -C build-deb_sram -j `nproc`

  build_rel:
    image: ${DOCKER_PREFIX}/gcc-arm-embedded
    pull: true
    commands:
      - cd project
      - cmake . -B build-rel -DCMAKE_BUILD_TYPE=Release
      - make -C build-rel -j `nproc`
      - cmake . -B build-rel_nor -DTARGET_NOR=ON -DUSE_DFU=ON -DCMAKE_BUILD_TYPE=Release
      - make -C build-rel_nor -j `nproc`
      - cmake . -B build-rel_sram -DTARGET_SRAM=ON -DCMAKE_BUILD_TYPE=Release
      - make -C build-rel_sram -j `nproc`

  deploy_rel:
    image: ${DOCKER_PREFIX}/network-utils
    pull: true
    commands:
      - cd project
      - source ./envvars
      - mkdir deploy
      - |
        for BUILD_DIR in "" "_nor" "_sram" ; do
          cd "build-rel$${BUILD_DIR}" && find . ! -path "*CMakeFiles*" -name "*.bin" | xargs tar -cvJ -f ../deploy/$${ARTIFACT_PREFIX}$${BUILD_DIR}.tar.xz && cd -
        done
      - cd deploy
      - smbclient "//$${DEPLOY_SERVER_ENV}" -U "$${DEPLOY_USER_NAME_ENV}%$${DEPLOY_USER_PASSWORD_ENV}" -c "mkdir ${CI_REPO_NAME}" || true
      - smbclient "//$${DEPLOY_SERVER_ENV}" -U "$${DEPLOY_USER_NAME_ENV}%$${DEPLOY_USER_PASSWORD_ENV}" -c "cd ${CI_REPO_NAME}; mkdir ${CI_COMMIT_BRANCH}" || true
      - smbclient "//$${DEPLOY_SERVER_ENV}" -U "$${DEPLOY_USER_NAME_ENV}%$${DEPLOY_USER_PASSWORD_ENV}" -c "cd ${CI_REPO_NAME}/${CI_COMMIT_BRANCH}; prompt; mput *"
    environment:
      DEPLOY_SERVER_ENV:
        from_secret: DEPLOY_SERVER
      DEPLOY_USER_NAME_ENV:
        from_secret: DEPLOY_USER_NAME
      DEPLOY_USER_PASSWORD_ENV:
        from_secret: DEPLOY_USER_PASSWORD
